# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-30 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_delete_screenname'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_date',
            field=models.DateTimeField(null=True, verbose_name='date played'),
        ),
    ]
