# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen_name', '0002_auto_20171230_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenname',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
